apiVersion: apps/v1
kind: Deployment
metadata:
  name: naveen-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: naveen
  template:
    metadata:
      labels:
        app: naveen
    spec:
      containers:
      - name: naveen-container
        image: ghcr.io/naveeng80/naveenworld:latestv1
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: github-naveen-secret