apiVersion: v1
kind: Secret
metadata:
  name: github-docker-secret
  namespace: default  # You can change this to your desired namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6ew0KICAgICJnaGNyLmlvIjogeyANCiAgICAgICAiYXV0aCI6ICJibUYyWldWdVp6Z3dPbWRvY0Y5RVJFUjJVMjk2Ym5VME5tVTFTbTVuV0U4eFpFSkdUMFpKVDB0RU5IRXhTRXgyV1c4PSINCgkgICB9DQoJICAgfQ0KCSAgIH0NCg0K